/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package agentdevanzarigui;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Eugen
 */
public class CheckUserIdentityPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckUserIdentityPanel
     */
    public CheckUserIdentityPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CheckUserNameLabel = new javax.swing.JLabel();
        CheckUserPasswordLabel = new javax.swing.JLabel();
        CheckUserNameField = new javax.swing.JTextField();
        CheckUserPasswordField = new javax.swing.JTextField();
        CheckUserLoginField = new javax.swing.JButton();
        CheckUserExitButton = new javax.swing.JButton();
        CheckUserLabel = new javax.swing.JLabel();

        CheckUserNameLabel.setText("Nume:");

        CheckUserPasswordLabel.setText("Parola:");

        CheckUserLoginField.setText("Login");
        CheckUserLoginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckUserLoginFieldActionPerformed(evt);
            }
        });

        CheckUserExitButton.setText("Exit");
        CheckUserExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckUserExitButtonActionPerformed(evt);
            }
        });

        CheckUserLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        CheckUserLabel.setText("       Check User Identity");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(68, 68, 68)
                        .add(CheckUserLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 265, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                            .add(90, 90, 90)
                            .add(CheckUserLoginField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(CheckUserExitButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                            .add(91, 91, 91)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(CheckUserNameLabel)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(CheckUserNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 163, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(layout.createSequentialGroup()
                                    .add(CheckUserPasswordLabel)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(CheckUserPasswordField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 163, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(CheckUserLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(CheckUserNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(CheckUserNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(CheckUserPasswordLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(CheckUserPasswordField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(CheckUserLoginField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(CheckUserExitButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CheckUserExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckUserExitButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AgentDeVanzariWindow().setVisible(true);

    }//GEN-LAST:event_CheckUserExitButtonActionPerformed

    private void CheckUserLoginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckUserLoginFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckUserLoginFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckUserExitButton;
    private javax.swing.JLabel CheckUserLabel;
    private javax.swing.JButton CheckUserLoginField;
    private javax.swing.JTextField CheckUserNameField;
    private javax.swing.JLabel CheckUserNameLabel;
    private javax.swing.JTextField CheckUserPasswordField;
    private javax.swing.JLabel CheckUserPasswordLabel;
    // End of variables declaration//GEN-END:variables


}
